name: Docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: bq-cloud-run
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
  CONTAINER: gcr.io/${PROJECT_ID}/${SERVICE}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/deploy-cloudrun@main
        with:
          service: bq-cloud-run
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build
        run: gcloud builds submit --tag ${CONTAINER} 
      
      - name: Push Docker image
        run: docker push ${CONTAINER} 
        
      - name: Deploy
        run: gcloud run deploy ${SERVICE} --image gcr.io/${PROJECT_ID}/${SERVICE} --platform managed --region $REGION --allow-unauthenticated

