name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    deploy:
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID}}/${{ secrets.GCP_APP_NAME }}
        steps:
        - name: Setup SDK
          uses: google-github-actions/setup-gcloud@v0.2.0
          with:
            version: "290.0.1"
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
            APP_ID: ${{ secrets.GCP_APP_NAME}}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            export_default_credentials: true 
            
        - name: Configure o Docker
          run: gcloud auth configure-docker

        - name: Build da imagem do Docker
          run: docker build --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

        - name: Push Docker image
          run: |
            docker push  $IMAGE_NAME:latest
          
        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.PROJECT_ID }} --image $IMAGE_NAME --region us-east1 --allow-unauthenticated

        - name: Show Output
          run: echo ${{ steps.deploy.outputs.url }}
