name: Docker
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: continous-deployment
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/deploy-cloudrun@main
        with:
          service: hello-cloud-run 
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
         gcloud auth configure-docker

      - name: Build
        run: |
         gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
         gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_REF
         gcloud config set run/region us-central1
        
      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_REF --platform managed --region $RUN_REGION --allow-unauthenticated
