name: Docker
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/deploy-cloudrun@main
        with:
          service: hello-cloud-run 
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
         gcloud auth configure-docker
         echo $service

      - name: Build
        run: |
         gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
         gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-cloud-run 
         gcloud config set run/region us-central1
        
      - name: Deploy
        run: gcloud run deploy hello-cloud-run --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/hello-cloud-run  --platform managed --region us-central1 --allow-unauthenticated
